spring:
  application:
    name: challenge

  datasource:
    url: jdbc:postgresql://postgres:5432/challenge
    username: postgres
    password: ${docker-secret-postgres-password:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariCP

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: redis
      port: 6379
      password: ${docker-secret-redis-password:password}

  kafka:
    bootstrap-servers: "kafka:9092"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  influx:
    metrics:
      export:
        enabled: false
        uri: "http://influx:8086"
        org: challenge
        bucket: challenge_metrics
        token: ${docker-secret-influxdb-token:token}
        api-version: v2

topics:
  telemetry-recorded: telemetry

docker-secret:
  bind-path: /run/secrets/